[package]
name = "dryrun"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rpc-server = { workspace = true }
jsonrpsee = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
